[dimensions]
Lx = 6.283185307179586
Ly = 6.283185307179586
Lz = 6.283185307179586

[parameters]
Ti_over_Te = 1.0
ion_charge = 1.0
rhoi = 0.0
de = 0.0
beta_over_mass_ratio = -1.0

[forcing]

# method = "elsasser"
energy_injection_rate = 0.1
injection_imbalance = 0.0
kperp_band = [1.0, 1.2]
kz_band = [1.0, 1.2]
